### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by sodnnddl** [Changbaiqi/yatori#22]
一共有四个课程，在每个课程刷完一个小结后停止显示异常：
Exception in thread "Thread-7" java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at com.cbq.yatori.core.action.yinghua.CourseStudyAction.study1(CourseStudyAction.java:96)
        at com.cbq.yatori.core.action.yinghua.CourseStudyAction.run(CourseStudyAction.java:80)
        at java.base/java.lang.Thread.run(Thread.java:833)
选择为英华，其他设置都为默认设置，关闭重新打开正常运行，请问是出现了什么问题

**Comment by Changbaiqi** [comment]
已修复，重新下载beta.8版本即可。
